spring:
  profiles:
    active: test
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      password: 1111
      name: user

  main:
    allow-bean-definition-overriding: true


  upload:
    dir: /path/upload
  logging:
    level:
      root: info

server:
  port : 8083
  forward-headers-strategy: native




